name: "MessagePacker CI"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  xcode:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          set -o pipefail
          xcodebuild test -scheme "MessagePacker" -destination "name=iPhone 8" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
          xcodebuild test -scheme "MessagePacker" -destination "arch=x86_64" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
          xcodebuild test -scheme "MessagePacker" -destination "name=Apple TV 4K" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
          xcodebuild build -scheme "MessagePacker" -destination "name=Apple Watch Series 4 - 44mm" -configuration Release ENABLE_TESTABILITY=YES | xcpretty

  swiftpm:
    runs-on: macos-latest
    name: SwiftPM
    steps:
      - uses: actions/checkout@v4
      - name: build and test
        run: |
          swift --version
          swift build
          swift test